---
title: "Exploring the data: distribution of biteforce and body size by diet"
author: "Natalie Cooper"
---

Load libraries
```{r}
library(ape)
library(tidyverse)
library(geiger)
library(tidytree)
library(treeio)
library(ggtree)
library(knitr)
library(ggstance)
library(patchwork)
library(here)

# Helper functions for plotting
remove_y <- 
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

remove_x <- 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

# Colour palette
diet_colours <- c("#D55E00", "#009E73", "#56B4E9")
```

Read in the data
```{r, message = FALSE}
ds1 <- read_csv(here("data/max_bf.csv"))

## Remove the species not in the tree and therefore not in the analyses
ds1 <-
  ds1 %>%
  filter(BinomialReptileDatabase != "Diplolaemus leopardinus" &
          BinomialReptileDatabase != "Tropidurus semitaeniatus" &
           BinomialReptileDatabase != "Aspidoscelis sonorae")

# Remove species with NAs for diet
ds1_diet <- filter(ds1, !is.na(Diet))
```

Extract mean BF and mean svl per diet
```{r}
diet_bf1 <-
  ds1_diet %>%
  group_by(Diet) %>%
  summarise(MeanBF = round(mean(log(max_bf)), digits = 3),
            SeBF = round(sd(log(max_bf))/sqrt(n()), digits = 3),
            MeanSVL = round(mean(log(max_svl)), digits = 3),
            SeSVL = round(sd(log(max_svl))/sqrt(n()), digits = 3),
            n())

````

```{r}
dietplot <-
  ggplot(ds1_diet, aes(x = log(max_bf), fill = Diet)) + 
  geom_density(alpha = 0.5, colour = NA) +
  scale_fill_manual(values = diet_colours) +
  theme_bw(base_size = 14) +
  xlab("ln(bite-force) (N)") + 
  xlim(-3, 7) +
  theme(legend.position = "right", legend.title = element_blank()) +
  labs(tag = "A") +
  theme(plot.tag = element_text(size = 12, face = "bold"),
        axis.title = element_text(size = 12)) 

dietplot2 <-
  ggplot(ds1_diet, aes(x = log(max_svl), fill = Diet)) + 
  geom_density(alpha = 0.5, colour = NA) +
  scale_fill_manual(values = diet_colours) +
  theme_bw(base_size = 14) +
  xlab("ln(SVL) (mm)") + 
  xlim(3, 6.5) +
  theme(legend.position = "right", legend.title = element_blank()) +
  labs(tag = "B") +
  theme(plot.tag = element_text(size = 12, face = "bold"),
        axis.title = element_text(size = 12)) 

dietplot / dietplot2

# Save the plot
# ggsave(here("figures/bf-svl-diet-plots.png"), height = 8)
```

