---
title: "Biteforce body size and acrodonty figures"
output: html_document
---

## Preparation

Load libraries
```{r}
library(ape)
library(tidyverse)
library(geiger)
library(tidytree)
library(treeio)
library(ggtree)
library(knitr)
library(caper)
library(ggstance)
library(patchwork)
library(here)

# Helper functions for plotting
remove_y <- 
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

remove_x <- 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

# Colour palette
sf_colours <- c("#ffc100", "#47b881", "#5588ff", 
                "#efbbff", "#ff7400", "#090088", "#800080")

# "Acrodonta"    #ffc100 = yellow   
# "Anguimorpha"     #47b881 = green
# "Dibamia"     "brown"    
# "Gekkota" #5588ff = lighter blue       
# "Lacertoidea"    #efbbff = pink
# "Pleurodonta"     #ff7400 = orange
# "Rhynchocephalia" #090088 = dark blue
# "Scincoidea" #800080 = purple

# Acrodont
a_colours <- c("#ffc100", "#ff7400")
```

Read in the data and ensure these are dataframes.
```{r, message = FALSE}
max_bf <- read_csv(here("data/max_bf.csv"))
max_bf <- data.frame(max_bf)
```

Make acrodont variable
```{r}
max_bf <-
  max_bf %>%
  mutate(acrodont = case_when(HigherTaxonomy == "Acrodonta" |
                              HigherTaxonomy == "Rhynchocephalia" ~ "Acrodont",
                              HigherTaxonomy != "Acrodonta" &
                              HigherTaxonomy != "Rhynchocephalia" ~ "Pleurodont"))
```

Read in phylogeny
```{r}
tree_plus <- read.nexus(here("data/lepidosaur-tree-plus.nex"))
```

Create comparative data objects with phylogeny and data combined
```{r}
lepidosaur <- comparative.data(phy = tree_plus, data = max_bf, 
                               names.col = tips, vcv = TRUE,
                               warn.dropped = FALSE, na.omit = FALSE)
```

Fit models to get regression lines
```{r}
# SVL
model1a <- pgls(log(max_bf) ~ log(max_svl)* as.factor(acrodont), data = lepidosaur,
                   lambda = "ML")

# HW
model2a <- pgls(log(max_bf) ~ log(max_hw)* as.factor(acrodont), data = lepidosaur,
                   lambda = "ML", bounds = list(lambda = c(0.1,1)))

# HL
model3a <- pgls(log(max_bf) ~ log(max_hl)* as.factor(acrodont), data = lepidosaur,
                   lambda = "ML")

# HH
model4a <- pgls(log(max_bf) ~ log(max_hh)* as.factor(acrodont), data = lepidosaur,
                   lambda = "ML")
```

Plots 

```{r}
svl <-
  ggplot(lepidosaur$data, aes(y = log(max_bf), x = log(max_svl), colour = acrodont)) + 
  geom_point(alpha = 0.5) +
  scale_colour_manual(values = a_colours) +
  theme_bw(base_size = 14) +
  xlab("ln(SVL) (mm)") +
  ylab("ln(bite-force) (N)") + 
  #ylim(-3, 6) +
  theme(legend.position = "right", legend.title = element_blank()) +
  labs(tag = "A") +
  theme(plot.tag = element_text(size = 12, face = "bold"),
        axis.title = element_text(size = 12),
        legend.position = "none") +
  geom_abline(intercept = coefficients(model1a)[1], 
              slope = coefficients(model1a)[2], colour = a_colours[1]) +
  geom_abline(intercept = coefficients(model1a)[1] + coefficients(model1a)[3], 
              slope = coefficients(model1a)[2] + coefficients(model1a)[4], colour = a_colours[2])

hw <-
  ggplot(lepidosaur$data, aes(y = log(max_bf), x = log(max_hw), colour = acrodont)) + 
  geom_point(alpha = 0.5) +
  scale_colour_manual(values = a_colours) +
  theme_bw(base_size = 14) +
  xlab("ln(head width) (mm)") +
  ylab("ln(bite-force) (N)") + 
  #ylim(-3, 6) +
  theme(legend.position = "right", legend.title = element_blank()) +
  labs(tag = "B") +
  theme(plot.tag = element_text(size = 12, face = "bold"),
        axis.title = element_text(size = 12),
        legend.position = "none") +
  geom_abline(intercept = coefficients(model2a)[1], 
              slope = coefficients(model2a)[2], colour = a_colours[1]) +
  geom_abline(intercept = coefficients(model2a)[1] + coefficients(model2a)[3], 
              slope = coefficients(model2a)[2] + coefficients(model2a)[4], colour = a_colours[2])
  
hl <-
  ggplot(lepidosaur$data, aes(y = log(max_bf), x = log(max_hl), colour = acrodont)) + 
  geom_point(alpha = 0.5) +
  scale_colour_manual(values = a_colours) +
  theme_bw(base_size = 14) +
  xlab("ln(head length) (mm)") +
  ylab("ln(bite-force) (N)") + 
  #ylim(-3, 6) +
  theme(legend.position = "right", legend.title = element_blank()) +
  labs(tag = "C") +
  theme(plot.tag = element_text(size = 12, face = "bold"),
        axis.title = element_text(size = 12),
        legend.position = "none") +
  geom_abline(intercept = coefficients(model3a)[1], 
              slope = coefficients(model3a)[2], colour = a_colours[1]) +
  geom_abline(intercept = coefficients(model3a)[1] + coefficients(model3a)[3], 
              slope = coefficients(model3a)[2] + coefficients(model3a)[4], colour = a_colours[2])
  
hh <-
  ggplot(lepidosaur$data, aes(y = log(max_bf), x = log(max_hh), colour = acrodont)) + 
  geom_point(alpha = 0.5) +
  scale_colour_manual(values = a_colours) +
  theme_bw(base_size = 14) +
  xlab("ln(head height) (mm)") +
  ylab("ln(bite-force) (N)") + 
  #ylim(-3, 6) +
  theme(legend.position = "right", legend.title = element_blank()) +
  labs(tag = "D") +
  theme(plot.tag = element_text(size = 12, face = "bold"),
        axis.title = element_text(size = 12))  +
  geom_abline(intercept = coefficients(model4a)[1], 
              slope = coefficients(model4a)[2], colour = a_colours[1]) +
  geom_abline(intercept = coefficients(model4a)[1] + coefficients(model4a)[3], 
              slope = coefficients(model4a)[2] + coefficients(model4a)[4], colour = a_colours[2])

(svl + hw) / (hl + hh)

# Save plot
#ggsave(here("figures/bodysize-bite-force-acrodont.png"), height = 5)
```

## Remove slopes...

```{r}
svl <-
  ggplot(lepidosaur$data, aes(y = log(max_bf), x = log(max_svl), colour = acrodont)) + 
  geom_point(alpha = 0.5) +
  scale_colour_manual(values = a_colours) +
  theme_bw(base_size = 14) +
  xlab("ln(SVL) (mm)") +
  ylab("ln(bite-force) (N)") + 
  #ylim(-3, 6) +
  theme(legend.position = "right", legend.title = element_blank()) +
  labs(tag = "A") +
  theme(plot.tag = element_text(size = 12, face = "bold"),
        axis.title = element_text(size = 12),
        legend.position = "none")

hw <-
  ggplot(lepidosaur$data, aes(y = log(max_bf), x = log(max_hw), colour = acrodont)) + 
  geom_point(alpha = 0.5) +
  scale_colour_manual(values = a_colours) +
  theme_bw(base_size = 14) +
  xlab("ln(head width) (mm)") +
  ylab("ln(bite-force) (N)") + 
  #ylim(-3, 6) +
  theme(legend.position = "right", legend.title = element_blank()) +
  labs(tag = "B") +
  theme(plot.tag = element_text(size = 12, face = "bold"),
        axis.title = element_text(size = 12),
        legend.position = "none") 
  
hl <-
  ggplot(lepidosaur$data, aes(y = log(max_bf), x = log(max_hl), colour = acrodont)) + 
  geom_point(alpha = 0.5) +
  scale_colour_manual(values = a_colours) +
  theme_bw(base_size = 14) +
  xlab("ln(head length) (mm)") +
  ylab("ln(bite-force) (N)") + 
  #ylim(-3, 6) +
  theme(legend.position = "right", legend.title = element_blank()) +
  labs(tag = "C") +
  theme(plot.tag = element_text(size = 12, face = "bold"),
        axis.title = element_text(size = 12),
        legend.position = "none") 
  
hh <-
  ggplot(lepidosaur$data, aes(y = log(max_bf), x = log(max_hh), colour = acrodont)) + 
  geom_point(alpha = 0.5) +
  scale_colour_manual(values = a_colours) +
  theme_bw(base_size = 14) +
  xlab("ln(head height) (mm)") +
  ylab("ln(bite-force) (N)") + 
  #ylim(-3, 6) +
  theme(legend.position = "right", legend.title = element_blank()) +
  labs(tag = "D") +
  theme(plot.tag = element_text(size = 12, face = "bold"),
        axis.title = element_text(size = 12))  

(svl + hw) / (hl + hh)

# Save plot
#ggsave(here("figures/bodysize-bite-force-acrodont-noslope.png"), height = 5)
```